# Generated by Django 4.2.4 on 2023-08-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_timestamp_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
