# Generated by Django 4.2.4 on 2023-08-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow_request', 'Follow Request'), ('follow_accept', 'Follow Request Accepted'), ('new_follower', 'New Follower'), ('new_comment', 'New Comment'), ('new_like', 'New Like')], max_length=20),
        ),
    ]
