# Generated by Django 4.2.4 on 2023-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_num_followers_user_num_following_user_num_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
