# Generated by Django 4.2.4 on 2023-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_media'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='core_hashta_name_9667f8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='core_post_user_id_0cf6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility'], name='core_post_visibil_0cd954_idx'),
        ),
    ]
