# Generated by Django 4.2.4 on 2023-09-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hashtag_core_hashta_name_9667f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='core_commen_post_id_6aa857_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='core_commen_created_97080c_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following', 'follow_status'], name='core_follow_followe_19509b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='core_messag_sender__064541_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver'], name='core_messag_receive_374293_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='core_notifi_recipie_9d58cb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', 'notification_type'], name='core_notifi_sender__31854c_idx'),
        ),
    ]
