# Generated by Django 4.2.4 on 2023-09-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_information',
        ),
    ]
