# Generated by Django 4.2.4 on 2023-09-03 00:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_user_contact_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(upload_to=core.models.post_media_upload),
        ),
    ]
